# Author: Ali Esbak
# Date: 6/1/2021

alterState:
  alter: Flase
  basePath_LabView_Scopes: ''
  broadcastMessage: False
  debugBit1: False    # Send Real Messages?
  debugBit2: False    # Print Debug Statements

# Labview Client portion - ideally part of a bigger configuration file 
LabViewClients:
  1:
    name: PI3_TCP_LV_Client
    active: True
    type: labView
    databases: 1
    connectionString: 172.25.226.222
    savePath: '/nfs/expdata/PI3'
    connectedDevices:
      # Armable scopes - Downloadable scopes
      Scopes:
        1:
          name: LeCroy_refINTERSCOPE1
          type: visa_lecroy
          connectionString: "TCPIP0::172.25.226.107::inst0::INSTR"
          #TIME_DIVS   = [
            # '1NS','2NS','5NS','10NS','20NS','50NS','100NS','200NS','500NS',
            # '1US','2US','5US','10US','20US','50US','100US','200US','500US',
            # '1MS','2MS','5MS','10MS','20MS','50MS','100MS','200MS','500MS',
            # '1S','2S','5S','10S','20S','50S','100S']
          timeDiv(s): 2MS
          # MEM_SIZE   = [
          #   '7K','14K','70K','140K','700K','1.4M','7M','14M','70M']
          memSize: 700K
          triggerType: External
          triggerLevel(mV): 600
          triggerDelay(s): 14MS
          triggerReference: Digitizer Timing
          activeChannels:
            - 1
            - 2
            - 3
            - 4
          ChannelSettings:
            1:
              name: IFxxx_CO2_refINTERSCOPE1
              vdiv(v): 5
              offset: 0
              coupling: D50
              BW: OFF
              probe: 1.0

            2:
              name: IF221_CO2
              vdiv(v): 20M
              offset: 0
              coupling: D50
              BW: OFF
              probe: 1.0

            3:
              name: IF239_CO2
              vdiv(v): 20M
              offset: 0
              coupling: D50
              BW: OFF
              probe: 1.0

            4:
              name: IF258_CO2
              vdiv(v): 20M
              offset: 0
              coupling: D50 
              BW: OFF
              probe: 1.0
        2:
          name: LeCroy_refINTERSCOPE2
          type: visa_lecroy
          connectionString: "TCPIP0::172.25.226.172::inst0::INSTR"
          #TIME_DIVS   = [
            # '1NS','2NS','5NS','10NS','20NS','50NS','100NS','200NS','500NS',
            # '1US','2US','5US','10US','20US','50US','100US','200US','500US',
            # '1MS','2MS','5MS','10MS','20MS','50MS','100MS','200MS','500MS',
            # '1S','2S','5S','10S','20S','50S','100S']
          timeDiv(s): 2MS
          # MEM_SIZE   = [
          #   '7K','14K','70K','140K','700K','1.4M','7M','14M','70M']
          memSize: 700K
          triggerType: External
          triggerLevel(mV): 600
          triggerDelay(s): 14MS
          triggerReference: Digitizer Timing
          activeChannels:
            - 1
            - 2
            - 3
          ChannelSettings:
            1:
              name: IFxxx_CO2_refINTERSCOPE2
              vdiv(v): 2
              offset: 0
              coupling: D50
              BW: OFF
              probe: 1.0

            2:
              name: IF267_CO2
              vdiv(v): 20M
              offset: 0
              coupling: D50
              BW: OFF
              probe: 1.0

            3:
              name: IF276_CO2
              vdiv(v): 20M
              offset: 0
              coupling: D50
              BW: OFF
              probe: 1.0
        3:
          name: LeCroy_refINTERSCOPE3
          type: visa_lecroy
          connectionString: "TCPIP0::172.25.226.106::inst0::INSTR"
          #TIME_DIVS   = [
            # '1NS','2NS','5NS','10NS','20NS','50NS','100NS','200NS','500NS',
            # '1US','2US','5US','10US','20US','50US','100US','200US','500US',
            # '1MS','2MS','5MS','10MS','20MS','50MS','100MS','200MS','500MS',
            # '1S','2S','5S','10S','20S','50S','100S']
          timeDiv(s): 2MS
          # MEM_SIZE   = [
          #   '7K','14K','70K','140K','700K','1.4M','7M','14M','70M']
          memSize: 700K
          triggerType: External
          triggerLevel(mV): 600
          triggerDelay(s): 14MS
          triggerReference: Digitizer Timing
          activeChannels:
            - 1
            - 2
            - 3
            - 4
          ChannelSettings:
            1:
              name: IFxxx_CO2_refINTERSCOPE2
              vdiv(v): 2
              offset: 0
              coupling: D50
              BW: OFF
              probe: 1.0

            2:
              name: IF221_HeNe
              vdiv(v): 20M
              offset: 0
              coupling: D50
              BW: OFF
              probe: 1.0

            3:
              name: IF239_HeNe
              vdiv(v): 200M
              offset: 0
              coupling: D50
              BW: OFF
              probe: 1.0
            4:
              name: IF258_HeNe
              vdiv(v): 200M
              offset: 0
              coupling: D50
              BW: OFF
              probe: 1.0

        4:
          name: LeCroy_refINTERSCOPE4
          type: visa_lecroy
          connectionString: "TCPIP0::172.25.226.128::inst0::INSTR"
          #TIME_DIVS   = [
            # '1NS','2NS','5NS','10NS','20NS','50NS','100NS','200NS','500NS',
            # '1US','2US','5US','10US','20US','50US','100US','200US','500US',
            # '1MS','2MS','5MS','10MS','20MS','50MS','100MS','200MS','500MS',
            # '1S','2S','5S','10S','20S','50S','100S']
          timeDiv(s): 2MS
          # MEM_SIZE   = [
          #   '7K','14K','70K','140K','700K','1.4M','7M','14M','70M']
          memSize: 700K
          triggerType: External
          triggerLevel(mV): 600
          triggerDelay(s): 14MS
          triggerReference: Digitizer Timing
          activeChannels:
            - 1
            - 2
            - 3
          ChannelSettings:
            1:
              name: IFxxx_CO2_refINTERSCOPE4
              vdiv(v): 1
              offset: 0
              coupling: D50
              BW: OFF
              probe: 1.0

            2:
              name: IF267_HeNe
              vdiv(v): 20M
              offset: 0
              coupling: D50
              BW: OFF
              probe: 1.0

            3:
              name: IF276_CO2
              vdiv(v): 20M
              offset: 0
              coupling: D50
              BW: OFF
              probe: 1.0
    services:
      BrightDetect:
        configVarPath: '/nfs/expdata/PI3/Configuration/brightdetect_vars.yml'
        active cams:
          - capCam1
          - capCam3
          - capCam5
        capCamConfigPath:
          capCam1: '/nfs/expdata/PI3/Configuration/CapCam1.yml'
          capCam3: '/nfs/expdata/PI3/Configuration/CapCam3.yml'
          capCam4: '/nfs/expdata/PI3/Configuration/CapCam4.yml'
          capCam5: '/nfs/expdata/PI3/Configuration/CapCam5.yml'



  2:
    name: Puff_Valve_Client
    active: True
    type: labView
    databases: 2
    connectionString: 172.25.226.222
    savePath: '/Data/ccs_utf'
    connectedDevices:
      # Armable scopes - Downloadable scopes
      Scopes: Null
  3:
    name: Test_TCP_LV_Client
    active: True
    type: labView
    databases: 2
    connectionString: 172.25.226.222
    savePath: '/Data/ccs_utf'
    connectedDevices:
      # Armable scopes - Downloadable scopes
      Scopes: Null
      capBankFD:
        database:
          - capbank_alarms_events
          - capbank_fault_detection
        detectors:
          1: 
            name: pi3_CBS_relay
            location: Bank_D
            connectionString: 172.25.226.222
            MACID: 000998AEBMW9
            active: True
          2:
            name: pi3_CBS_008
            location: Bank_D
            connectionString: 172.25.226.222
            MACID: 000998AEBMW8
            active: False

  
Databases:
  1:
    name: plasmaInjector_3
    user: root
    password: 123
    host: 172.30.5.1
    port: 3307
    tables:
      - capbank_alarms_events:
        - event_id
        - timeStamp
        - client
        - sensor
        - alarm
      - capbank_fault_detection:
        - event_id
        - timeStamp
        - client
        - sensor
        - event
        - stae
      - events:
        - event_id
        - timeStamp
        - name
        - description
      - tag_history:
        - tag_id
        - timeStamp
        - name
        - value
        - status