# Author: Ali Esbak
# Date: 6/1/2021

alterState:
  alter: Flase
  basePath_LabView_Scopes: ''
  broadcastMessage: False
  
# Labview Client portion - ideally part of a bigger configuration file 
LabViewClients:
  1:
    name: PI3_TCP_LV_Client
    active: True
    type: labView
    databases: 1
    connectionString: 172.25.226.222
    savePath: 'C:\Users\ali.esbak\Desktop\PythonDAQ\Data' #'/Data/ccs_utf' #
    connectedDevices:
      # Armable scopes - Downloadable scopes
      Scopes:
        1:
          name: LeCroy_InterScope1
          type: visa_lecroy
          connectionString: "TCPIP0::172.25.226.126::inst0::INSTR"
          #TIME_DIVS   = [
            # '1NS','2NS','5NS','10NS','20NS','50NS','100NS','200NS','500NS',
            # '1US','2US','5US','10US','20US','50US','100US','200US','500US',
            # '1MS','2MS','5MS','10MS','20MS','50MS','100MS','200MS','500MS',
            # '1S','2S','5S','10S','20S','50S','100S']
          timeDiv(s): 2MS
          memSize: 700K
          triggerType: External
          triggerLevel(mV): 600
          triggerDelay(s): 0.0
          triggerReference: Digitizer Timing
          activeChannels:
            - 1
            - 2
            - 3
          ChannelSettings:
            1:
              name: Channel 1
              vdiv(v): 10
              offset: 0
            2:
              name: Channel 2
              vdiv(v): 5
              offset: 0
            3:
              name: Channel 3
              vdiv(v): 44
              offset: 0
  2:
    name: Puff_Valve_Client
    active: True
    type: labView
    databases: 2
    connectionString: 172.25.226.222
    savePath: '/Data/ccs_utf'
    connectedDevices:
      # Armable scopes - Downloadable scopes
      Scopes: Null

Databases:
  1:
    name: plasmaInjector_3
    user: root
    password: 123
    host: 172.30.5.1
    port: 3307
    tables:
      - capbank_alarms_events:
        - event_id
        - timeStamp
        - client
        - sensor
        - alarm
      - capbank_fault_detection:
        - event_id
        - timeStamp
        - client
        - sensor
        - event
        - stae
      - events:
        - event_id
        - timeStamp
        - name
        - description
      - tag_history:
        - tag_id
        - timeStamp
        - name
        - value
        - status

