# Author: Ali Esbak
# Date: 6/1/2021

alterState:
  alter: Flase
  basePath_LabView_Scopes: ''
  broadcastMessage: False
  debugBit1: False    # Send Real Messages?
  debugBit2: False    # Print Debug Statements

# Labview Client portion - ideally part of a bigger configuration file 
LabViewClients:
  1:
    name: PI3_TCP_LV_Client
    active: True
    type: labView
    databases: 1
    connectionString: 172.25.226.222
    savePath: '/nfs/expdata/PI3'
    connectedDevices:
      # Armable scopes - Downloadable scopes
      Scopes:
        1:
          name: scint_144
          type: visa_lecroy
          connectionString: "TCPIP0::172.25.226.172::inst0::INSTR"
          #TIME_DIVS   = [
            # '1NS','2NS','5NS','10NS','20NS','50NS','100NS','200NS','500NS',
            # '1US','2US','5US','10US','20US','50US','100US','200US','500US',
            # '1MS','2MS','5MS','10MS','20MS','50MS','100MS','200MS','500MS',
            # '1S','2S','5S','10S','20S','50S','100S']
          timeDiv(s): 2MS
          #MEM_SIZE   = [
            # '7K','14K','70K','140K','700K','1.4M','7M','14M','70M']
          memSize: 14M
          triggerType: External
          triggerLevel(mV): 100MV
          triggerDelay(s): 14MS
          triggerReference: Digitizer Timing
          activeChannels:
            - 1
            - 2
            - 3
            - 4
          ChannelSettings:
            1:
              name: Scint_SC9
              vdiv(v): 75MV
              offset: 0
              coupling: D50
              BW: OFF
              probe: 1.0
            2:
              name: Scint_SC9Zoom
              vdiv(v): 2MV
              offset: 0
              coupling: D50
              BW: OFF
              probe: 1.0

            3:
              name: Scint_SC10
              vdiv(v): 50MV
              offset: 0
              coupling: D50
              BW: OFF
              probe: 1.0

            4:
              name: Scint_SC10Zoom
              vdiv(v): 2MV
              offset: 0
              coupling: D50
              BW: OFF
              probe: 1.0

        2:
          name: scint_146
          type: visa_lecroy
          connectionString: "TCPIP0::172.25.226.128::inst0::INSTR"
          #TIME_DIVS   = [
            # '1NS','2NS','5NS','10NS','20NS','50NS','100NS','200NS','500NS',
            # '1US','2US','5US','10US','20US','50US','100US','200US','500US',
            # '1MS','2MS','5MS','10MS','20MS','50MS','100MS','200MS','500MS',
            # '1S','2S','5S','10S','20S','50S','100S']
          timeDiv(s): 2MS
          #MEM_SIZE   = [
            # '7K','14K','70K','140K','700K','1.4M','7M','14M','70M']
          memSize: 14M
          triggerType: External
          triggerLevel(mV): 100MV
          triggerDelay(s): 14MS
          triggerReference: Digitizer Timing
          activeChannels:
            - 1
            - 2
            - 3
            - 4
          ChannelSettings:
            1:
              name: Scint_SC13
              vdiv(v): 75MV
              offset: 0
              coupling: D50
              BW: OFF
              probe: 1.0
            2:
              name: Scint_SC13Zoom
              vdiv(v): 2MV
              offset: 0
              coupling: D50
              BW: OFF
              probe: 1.0

            3:
              name: Scint_SC16
              vdiv(v): 20MV
              offset: 0
              coupling: D50
              BW: OFF
              probe: 1.0

            4:
              name: Scint_SC16Zoom
              vdiv(v): 2MV
              offset: 0
              coupling: D50
              BW: OFF
              probe: 1.0

        3:
          name: Vloop_1
          type: visa_lecroy
          connectionString: "TCPIP0::172.25.226.114::inst0::INSTR"
          #TIME_DIVS   = [
            # '1NS','2NS','5NS','10NS','20NS','50NS','100NS','200NS','500NS',
            # '1US','2US','5US','10US','20US','50US','100US','200US','500US',
            # '1MS','2MS','5MS','10MS','20MS','50MS','100MS','200MS','500MS',
            # '1S','2S','5S','10S','20S','50S','100S']
          timeDiv(s): 5MS
          # MEM_SIZE   = [
          #   '7K','14K','70K','140K','700K','1.4M','7M','14M','70M']
          memSize: 700K
          triggerType: External
          triggerLevel(mV): 600
          triggerDelay(s): 34MS
          triggerReference: Digitizer Timing
          activeChannels:
            - 1
            - 2
            - 3
          ChannelSettings:
            1:
              name: EXTLOOPVOLTAGE284
              vdiv(v): 500MV
              offset: 0
              coupling: D50
              BW: OFF
              probe: 1.0

            2:
              name: EXTLOOPVOLTAGE155
              vdiv(v): 500MV
              offset: 0
              coupling: D50
              BW: OFF
              probe: 1.0

            3:
              name: EXTLOOPVOLTAGE201
              vdiv(v): 500MV
              offset: 0
              coupling: D50
              BW: OFF
              probe: 1.0

  2:
    name: Puff_Valve_Client
    active: True
    type: labView
    databases: 2
    connectionString: 172.25.226.222
    savePath: '/Data/ccs_utf'
    connectedDevices:
      # Armable scopes - Downloadable scopes
      Scopes: Null
  3:
    name: Test_TCP_LV_Client
    active: True
    type: labView
    databases: 2
    connectionString: 172.25.226.222
    savePath: '/Data/ccs_utf'
    connectedDevices:
      # Armable scopes - Downloadable scopes
      Scopes: Null
Databases:
  1:
    name: plasmaInjector_3
    user: root
    password: 123
    host: 172.30.5.1
    port: 3307
    tables:
      - capbank_alarms_events:
        - event_id
        - timeStamp
        - client
        - sensor
        - alarm
      - capbank_fault_detection:
        - event_id
        - timeStamp
        - client
        - sensor
        - event
        - stae
      - events:
        - event_id
        - timeStamp
        - name
        - description
      - tag_history:
        - tag_id
        - timeStamp
        - name
        - value
        - status